Online-Shop/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Online_Shop.Models
{
    public class Product : BaseEntity
    {
        [Key]
        public int ProductId { get; set; }
        [Required]
        [MinLength(2)]
        [MaxLength(50)]
        public string Marka { get; set; }
        [Required]
        [MinLength(2)]
        [MaxLength(50)]
        public string Modeli { get; set; }
        [Required]
        [MinLength(2)]
        [MaxLength(50)]
        public string Ngjyra { get; set; }
        [Required]
        public string Image { get; set; }
        [Required]
        [Range(0, 9999.99)]
        public double Price { get; set; }
        [Required]
        public int? CategoryId { get; set; }
        public  Category Category  { get; set; }
    }
}

Online-Shop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Online_Shop.Data;
using Online_Shop.Models;
using Online_Shop.Utilityy;

namespace OnlineShop.Areas.Customer.Controllers
{
   
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderController(ApplicationDbContext context)
        {
            _context = context;
        }

        //GET Checkout actioin method

        public IActionResult Checkout()
        {
            return View();
        }
        public IActionResult ThankYou()
        {
            return View();
        }

        //POST Checkout action method

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Checkout([Bind("Id","OrderNo","Name","PhoneNo","Email","Address","OrderDate")] Order anOrder)
        {
            List<Product> products = HttpContext.Session.Get<List<Product>>("products");
            
            if (products != null)
            {
                foreach (var product in products)
                {
                    OrderDetails orderDetails = new OrderDetails();
                    orderDetails.ProductId = product.ProductId;
                    anOrder.OrderDetails.Add(orderDetails);
                }
            }
            if (anOrder.Name == null || anOrder.Name.Trim().Equals(""))
            {
                return View();
            }else if (anOrder.PhoneNo == null || anOrder.PhoneNo.Trim().Equals(""))
            {
                return View();
            }else if (anOrder.Email == null || anOrder.Email.Trim().Equals(""))
            {
                return View();
            }else if (anOrder.Address== null || anOrder.Address.Trim().Equals(""))
            {
                return View();
            }else if(anOrder.OrderDate == null || anOrder.OrderDate == default(DateTime) )
            {
                return View();
            }


            anOrder.OrderNo = GetOrderNo();
            _context.Orders.Add(anOrder);
            await _context.SaveChangesAsync();
            HttpContext.Session.Set("products", new List<Product>());
            return RedirectToAction(nameof(ThankYou));
        }


        public string GetOrderNo()
        {
            int rowCount = _context.Orders.ToList().Count() + 1;
            return rowCount.ToString("000");
        }
    }
    
}

Online-Shop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Online_Shop.Data;
using Online_Shop.Models;
using Online_Shop.Utilityy;

namespace Online_Shop.Controllers
{
 
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        

        // GET: Products
        [AllowAnonymous]
        public ActionResult Index(int pg = 1, string search = "")
        {
            List<Product> laptops = _context.Products.ToList();
            List<Product> laptopat = _context.Products.Where(x => x.Marka.Contains(search)).ToList();

            if (search == "")
            {
                const int pageSize = 6;
                if (pg < 1)
                {
                    pg = 1;
                }

                int recsCount = laptops.Count();

                var pager = new Pager(recsCount, pg, pageSize);

                int recSkip = (pg - 1) * pageSize;

                var data = laptops.Skip(recSkip).Take(pager.PageSize).ToList();

                this.ViewBag.Pager = pager;

                //return View(laptops);

                return View(data);

            }
            if (_context.Products.Where(x => x.Marka.Contains(search)).ToList() != null)
            {
                //const int pageSize = 3;
                if (pg < 1)
                {
                    pg = 1;
                }

                //int recsCount = laptopat.Count();

                //var pager = new Pager(recsCount, pg, pageSize);

                //int recSkip = (pg - 1) * pageSize;

                //var data = laptopat.Skip(recSkip).Take(pager.PageSize).ToList();

                //this.ViewBag.Pager = pager;

                //return View(data);
                return View(_context.Products.Where(x => x.Marka.Contains(search)).ToList());
            }

            return View(_context.Products.Where(x => x.Marka.Contains(search)).ToList());
        }


        // GET: Products/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            
            var product = _context.Products
                .Include(c => c.Category)
                .FirstOrDefault(c => c.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }


        //POST: Product/Details/id
        [HttpPost]
        [ActionName("Details")]
        public ActionResult ProductDetails(int? id)
        {
            List<Product> products = new List<Product>();
            if (id == null)
            {
                return NotFound();
            }

            var product =  _context.Products
                .Include(c => c.Category)
                .FirstOrDefault(c => c.ProductId == id);
            
            if (product == null)
            {
                return NotFound();
            }
            products = HttpContext.Session.Get<List<Product>>("products");
            if (products == null) {
                products = new List<Product>();
            }
            products.Add(product);
            HttpContext.Session.Set("products", products);
            return View(product);

        }

        //Get Remove action Method
        [ActionName("Remove")]
        public IActionResult RemoveToCart(int? id)
        {
            List<Product> products = HttpContext.Session.Get<List<Product>>("products");
            if (products != null)
            {
                var product = products.FirstOrDefault(c => c.ProductId == id);
                if (product != null)
                {
                    products.Remove(product);
                    HttpContext.Session.Set("products", products);
                }
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]

        public IActionResult Remove(int? id)
        {
            List<Product> products = HttpContext.Session.Get<List<Product>>("products");
            if(products != null)
            {
                var product = products.FirstOrDefault(c => c.ProductId == id);
                if(product != null)
                {
                    products.Remove(product);
                    HttpContext.Session.Set("products", products);
                }
            }

            return RedirectToAction(nameof(Index));
        }
        // GET: Products/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProdictId,Marka,Modeli,Ngjyra,Image,Price,CategoryId,CreatedBy,CreatedDate,UpdatedBy,UpdatedDate")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", product.CategoryId);
            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", product.CategoryId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,Marka,Modeli,Ngjyra,Image,Price,CategoryId,CreatedBy,CreatedDate,UpdatedBy,UpdatedDate")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", product.CategoryId);
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }

        public IActionResult Cart()
        {
            List<Product> products = HttpContext.Session.Get<List<Product>>("products");
            if( products == null)
            {
                products = new List<Product>();
            }
            return View(products);
        }
    }
}

Online-Shop/Views/Products/Cart.cshtml
@using Online_Shop.Models
@model List<Product>
    @{
        ViewData["Title"] = "Cart";
    }

    <!-- Hero Area Start-->
    <div class="slider-area ">
        <div class="single-slider slider-height2 d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center">
                            <h2>Cart</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Hero Area End-->
    <br />
    <br />
    <br />

    <div class="container">
        <table class="table table-bordered">
            <thead>
                
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <img src="~/theme/assets/img/gallery/@item.Image" width="200" height="150" />
                        </td>
                        <td>@item.Marka</td>
                        <td>@item.Modeli</td>
                        <td>@item.Ngjyra</td>
                        <td>@item.CategoryId</td>
                        <td>@item.Price $</td>
                        <td>
                            <a asp-area="" asp-action="Remove" asp-controller="Products" asp-route-id="@item.ProductId">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <div class="row">
            <div class="col-6">
                <a asp-action="Index" asp-controller="Products" class="button button-contactForm boxed-btn">Back to Home</a>
            </div>
            <div class="col-6 text-right">
                <h3>Total Amount: @Model.Sum(c => c.Price)$</h3>
                @if (@Model.Sum(c => c.Price) != 0)
                {
                <a asp-action="Checkout" asp-controller="Order" class="button button-contactForm boxed-btn">Proceed to Checkout</a>
                }
            </div>
        </div>
    </div>

Online-Shop/Views/Products/Create.cshtml
@model Online_Shop.Models.Product

@{
    ViewData["Title"] = "Create";
}

<!-- Hero Area Start-->
<div class="slider-area ">
    <div class="single-slider slider-height2 d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>Create Product</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Hero Area End-->
<br />
<br />
<br />
<div class="row">
    <div class="col-md-4" style="margin-right:auto; margin-left:auto;">
        <form asp-action="Create" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marka" class="control-label"></label>
                <input asp-for="Marka" class="form-control" />
                <span asp-validation-for="Marka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modeli" class="control-label"></label>
                <input asp-for="Modeli" class="form-control" />
                <span asp-validation-for="Modeli" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ngjyra" class="control-label"></label>
                <input asp-for="Ngjyra" class="form-control" />
                <span asp-validation-for="Ngjyra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" type="file" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="button button-contactForm boxed-btn" />
            </div>
        </form>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Online-Shop/Views/Products/Delete.cshtml
@model Online_Shop.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<!-- Hero Area Start-->
<div class="slider-area ">
    <div class="single-slider slider-height2 d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>Delete Product</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Hero Area End-->
<br />
<br />
<br />
<div>
    <div class="col-md-4" style="margin-right:auto; margin-left:auto;">
        <h3>Are you sure you want to delete this?</h3>
        <br />

        <div class="single-new-pro mb-30 text-center">
            <div class="product-img">
                <img src="~/theme/assets/img/gallery/@Html.DisplayFor(model => model.Image)" alt="">
            </div>
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Marka)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Marka)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Modeli)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Modeli)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Ngjyra)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Ngjyra)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Image)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Image)
                </dd>

                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Price)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Price)
                </dd>
                <dd>
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="ProductId" />
                        <a asp-action="Index">Back to List</a>
                        <input type="submit" value="Delete" class="button button-contactForm boxed-btn" />
                    </form>
                </dd>
            </dl>
        </div>
    </div>
    <br />

</div>

Online-Shop/Views/Products/Details.cshtml
@model Online_Shop.Models.Product
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@using Online_Shop.Utilityy
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccesor
@{
    
    List<Product> products = HttpContextAccesor.HttpContext.Session.Get<List<Product>>("products");
    Product product = null;
    if (products != null)
    {
        product = products.FirstOrDefault(c => c.ProductId == Model.ProductId);
    }
    
}
@{
    ViewData["Title"] = "Details";
}

<!-- Hero Area Start-->
<div class="slider-area ">
    <div class="single-slider slider-height2 d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>Product Details</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Hero Area End-->
<br />
<br />
<br />
<div class="col-md-4" style="margin-right:auto; margin-left:auto;">
    <div class="single-new-pro mb-30 text-center">
        <div class="product-img">
            <a data-fancybox="chair" href="~/theme/assets/img/gallery/@Html.DisplayFor(model => model.Image)" data-caption="@Html.DisplayFor(model => model.Marka) @Html.DisplayFor(model => model.Modeli)"><img src="~/theme/assets/img/gallery/@Html.DisplayFor(model => model.Image)"></a>
        </div>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Marka)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Marka)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Modeli)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Modeli)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Ngjyra)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Ngjyra)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Image)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Image)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Category.CategoryName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Category.CategoryName)
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)$
            </dd>
            <dd>
                <div>
                    <form method="post" asp-controller="Products" asp-action="Details" enctype="multipart/form-data">
                        @if (product != null)
                        {
                            <button type="submit" class="button button-contactForm boxed-btn" asp-action="Remove" asp-route-id="@Model.ProductId">Remove from Cart</button>
                        }
                        else
                        {
                            <input type="submit" class="button button-contactForm boxed-btn" value="Add to Cart" />
                        }
                        <a class="button button-contactForm boxed-btn" asp-action="Index">Back to List</a>
                    </form>
                        @if (String.Equals(@Model.CreatedBy, @User.Identity.Name) || User.IsInRole("Editor") || User.IsInRole("Admin"))
                        {
                            <a class="button button-contactForm boxed-btn" asp-action="Edit" asp-route-id="@Model.ProductId">Edit</a>
                            <a class="button button-contactForm boxed-btn" asp-action="Delete" asp-route-id="@Model.ProductId">Delete</a>
                        }

                       
                    
                </div>
            </dd>
        </dl>
    </div>
</div>

Online-Shop/Views/Products/Edit.cshtml
@model Online_Shop.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<!-- Hero Area Start-->
<div class="slider-area ">
    <div class="single-slider slider-height2 d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>Edit Product</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Hero Area End-->
<br />
<br />
<br />
<hr />
<div class="row">
    <div class="col-md-4" style="margin-right:auto; margin-left:auto;">
        <form asp-action="Edit" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId" />
            <div class="form-group">
                <label asp-for="Marka" class="control-label"></label>
                <input asp-for="Marka" class="form-control" />
                <span asp-validation-for="Marka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modeli" class="control-label"></label>
                <input asp-for="Modeli" class="form-control" />
                <span asp-validation-for="Modeli" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ngjyra" class="control-label"></label>
                <input asp-for="Ngjyra" class="form-control" />
                <span asp-validation-for="Ngjyra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" type="file" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="button button-contactForm boxed-btn" />
            </div>
        </form>
        <a asp-action="Index">Back to List</a>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Online-Shop/Views/Products/Index.cshtml
@model IEnumerable<Online_Shop.Models.Product>

@{
    ViewData["Title"] = "Products";

    Pager pager = new Pager();

    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<!-- Hero Area Start-->
<div class="slider-area ">
    <div class="single-slider slider-height2 d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>Products</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Hero Area End-->

<section class="new-product-area section-padding30">
    <div class="container">
        <!-- Section tittle -->
        <div class="row">
            <div class="col-xl-12">
                <div class="section-tittle mb-70">
                    <h2>Latest Deals</h2>
                </div>
                <p>
                    <a asp-action="Create">Create New</a>
                </p>
            </div>
            <p>
                @using (@Html.BeginForm())
                {
                    @Html.TextBox("search") <input class="button button-contactForm boxed-btn" type="submit" value="Search" />
                }

            
            <br />
            <div class="row pt-5">

                @foreach (var item in Model)
                {
                    <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
                        <div class="single-new-pro mb-30 text-center">
                            <div class="product-img">
                                <a data-fancybox="chair" href="~/theme/assets/img/gallery/@Html.DisplayFor(modelItem => item.Image)" data-caption="@Html.DisplayFor(modelItem => item.Marka) @Html.DisplayFor(modelItem => item.Modeli)"><img src="~/theme/assets/img/gallery/@Html.DisplayFor(modelItem => item.Image)"></a>
                            </div>
                            <div class="product-caption">
                                <h3><a asp-action="Details" asp-route-id="@item.ProductId">@Html.DisplayFor(modelItem => item.Marka)</a></h3>
                                <span>@Html.DisplayFor(modelItem => item.Price)$</span>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <partial name="_pager" model="@pager" />
        </div>
    </div>
</section>
<!--  New Product End -->